/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.domino.config;

import org.mule.api.MuleEvent;
import org.mule.construct.SimpleFlowConstruct;
import org.mule.tck.FunctionalTestCase;

public class DominoNamespaceHandlerTestCase extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return "domino-namespace-config.xml";
    }

    public void testCRUD()throws Exception
    {
        SimpleFlowConstruct flow = lookupFlowConstruct("createFlow");
		MuleEvent event = getTestEvent(null);
        MuleEvent responseEvent = flow.process(event);
        assertNotNull(responseEvent);
        assertNotNull(responseEvent.getMessage().getPayload());
        assertTrue(responseEvent.getMessage().getPayload() instanceof Boolean);
    }

    private SimpleFlowConstruct lookupFlowConstruct(String name)
    {
        return(SimpleFlowConstruct)muleContext.getRegistry().lookupFlowConstruct(name);
    }
    
}
